version: 2.1

jobs:
  test_python:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Run Tests
          command: python -m unittest
          working_directory: ~/project/python
  make:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pipenv install
      - run:
          name: Make Snippets
          command: pipenv run python make.py
      - store_artifacts:
          path: json

workflows:
  test_and_make:
    jobs:
      - test_python
      - make
