version: 2.1

jobs:
  test_python:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install All Dependencies
          command: pipenv install --dev
      - run:
          name: Run Tests
          command: pipenv run test
          working_directory: ~/project/python
      - run:
          name: codecov
          command: pipenv run codecov
          working_directory: ~/project/python
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pipenv install
      - run:
          name: Make Snippets
          command: pipenv run build
      - store_artifacts:
          path: json

workflows:
  build:
    jobs:
      # - test_python
      - build
